version: "3"
services: 
  fr24:
    build:
      context: ./fr24
    env_file: mac.env
    # environment:
    #   - FR24KEY=xyz
    #   - BEASTHOST=127.0.0.1
    #   - MLAT=yes
    ports:
      - 30334:30334
      - 8754:8754
      - 30003:30003
  adsbexchange:
    build:
      context: ./adsbexchange
    env_file: mac.env
    # environment:
    #   - FR24KEY=xyz
    #   - BEASTHOST=127.0.0.1
    #   - MLAT=yes
    ports:
      - 8080:8080
      