version: "3"
services: 
  fr24:
    build:
      context: ./fr24
    env_file: mac.env
    ports:
      - 30334:30334
      - 8754:8754
      - 30003:30003
  adsbexchange:
    build:
      context: ./adsbexchange
    env_file: mac.env
    ports:
      - 8080:8080
  adsbexchange-mlat:
    build:
      context: ./adsbexchange-mlat
    env_file: mac.env
    ports:
      - 8080:8080