apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adsbexchange.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adsbexchange.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "adsbexchange.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "adsbexchange.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "adsbexchange.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /radar
              port: http
          readinessProbe:
            httpGet:
              path: /radar
              port: http
          env:
            - name: BEASTHOST
              value: "{{ .Values.beast.host }}"
            - name: BEASTPORT
              value: "{{ .Values.beast.port }}"
            - name: LAT
              value: "{{ .Values.location.latitude }}"
            - name: LONG
              value: "{{ .Values.location.longitude }}"
            - name: UUID
              value: "{{ .Values.uuid }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
